cro: 1
id: sparkyci
name: SparkyCI
entrypoint: app.raku
ignore:
  #- projects
  - sparky/
  #- .cache
  #- .tom
  - README.md
  - utils/
  #- run.sh
  #- sparrowfile
  #- t/
  #- db-init.raku
  #- META6.json
  #- .gitignore
