init:
  services:
    mysql:
      db-user: $DB_USER
      db-password: $DB_PASS

  script: |
    echo $DB_USER
    cp t/.my.cnf ~

  variables:
    DB_USER: sparky
    DB_PASS: sparky123

main:
  with-code-coverage: false
